### ISSUE TITLE
Add ability to manually add new incidents

### ISSUE THREAD

**Issue by ivantn21** [alertmanager/alert_manager#124]
There are occasions where we want to add a new incident manually that we might have discovered during the execution of behavioral analysis outside of scheduled searches. This feature will allow analysts to track such events the same way as other events. Maybe this can be implemented on the incident review dashboard? Thanks! This is a great App and we look forward to future development!

**Comment by simcen** [comment]
Great suggestion, thanks!

**Comment by my2ndhead** [comment]
Done
