### ISSUE TITLE
display field issue

### ISSUE THREAD

**Issue by TheFausap** [alertmanager/alert_manager#241]
Hello
I'm trying to use the display field setting to add more information in the Incident Posture window.
I configured the setting, but no fields are displayed.
I tried using directly the field name (it's not a metadata field, it's a field result from the search) or the $result.<fieldname>$ (this is working fine in the title) with no luck.

I checked also in the docs, but it's quite vague.

Where's my error?

thanks
Fausto

**Comment by my2ndhead** [comment]
The display fields are just the field names from the results, separated by space, e.g.:

count host
