### ISSUE TITLE
Splunk 2.3 app

### ISSUE THREAD

**Issue by b4b857f6ee** [alertmanager/alert_manager#246]
Hello,

On the Splunkbase, the app is still in 2.2.2, any ETA to upload the 2.3.0? :)

Best regards

**Comment by my2ndhead** [comment]
No ETA yet, due to time-constraints. The current develop branch is used in production. It lacks proper update testing and documentation. This is preventing an update on Splunkbase.

A sponsorship could speed things up also in regards of Python 3 compatibility :-)

**Comment by my2ndhead** [comment]
See #248
