### ISSUE TITLE
Compatibility with Splunk 8.x

### ISSUE THREAD

**Issue by jverma19** [alertmanager/alert_manager#248]
Hello,

We're going to upgrade to Splunk 8.x soon in our environment. I was wondering if the current version of Alert manager would be compatible with it or not. If not, when can we expect the compatible version on the Splunkbase. :)

Thank you,

**Comment by PaleWooten** [comment]
Hi! 

Im using 2.1.3 and upgrade it to 2.2.2 on splunk 8.0.1 - ive encountered some problems:
1. For some strange reasons my KV store collections with INcident settings wont work,unless i change enforceTypes in collection.conf to false
2. Saving Incident settings dont work anyway,we change them via lookup. 

But i ve got this problems only on my prod instance,on tests - all was fine

**Comment by JensHaizmann** [comment]
> Hello,
> 
> We're going to upgrade to Splunk 8.x soon in our environment. I was wondering if the current version of Alert manager would be compatible with it or not. If not, when can we expect the compatible version on the Splunkbase. :)
> 
> Thank you,

Same question from me. I'll appreciate an answer since we have to upgrade as well.

**Comment by my2ndhead** [comment]
Sorry for the delay.

- The current Splunkbase release should be compatible with 8.0 ( with Python 2.7). No thorough testing has been done, but I can't think of any bigger problems to occure.

- I'm targetting a Alert Manager 3.0 release by End of May (Python 3.7 only). This will roughly reflect what's on the develop branch. This will be also (and finally) pushed to Splunkbase.

Hope this helps!

**Comment by my2ndhead** [comment]
Alert Manager 3.0.0 released
