### ISSUE TITLE
Intermittent Alert results display and details

### ISSUE THREAD

**Issue by hurculeasz** [alertmanager/alert_manager#255]
On the incident posture screen, if I select an incident, the Alert Results area at the bottom sometimes gives a No Results found. Using the refresh for that table will sometimes get the Alert results to display. This is also the case with Details in the drill down also. This happens intermittently on all incidents. There does not seem to be any rhyme or reason to this. Sometimes refreshing multiple times does not help.

Using loadincidentresults manually is the same. Sometimes it returns and other times it does not. 

I do have Save incident results to KVStore checked and I also had Index incident results checked. 

This is version 2.2.2
![image](https://user-images.githubusercontent.com/62719524/83785920-ddf58c80-a646-11ea-9e6b-31f266ef5bd2.png)

![image](https://user-images.githubusercontent.com/62719524/83785991-f2d22000-a646-11ea-8566-717dfa91de97.png)

**Comment by hurculeasz** [comment]
I have upgrade to version 3.1 and still see the same issue. When I first open the page, I can select a specific incident and the drill down shows the details. If I reopen the drill down on the same incident I do not get details. I do not see anything that signifies an error. 

I do have both Save incident results to KVStore: and Save incident results to Index: checked. I index them as I have altered the alert results query on the bottom of the posture page to pull form the index to easily show an admin the associated alert.

Thanks!

**Comment by my2ndhead** [comment]
Hi @hurculeasz 

I've seen some strange issues on Windows with the custom command fetching the data. I rewrote those commands today. Can you try if 3.0.3 solves this? Not yet on Splunkbase...

[alert_manager-3.0.3.tar.gz](https://github.com/alertmanager/alert_manager/files/4899326/alert_manager-3.0.3.tar.gz)

**Comment by hurculeasz** [comment]
@my2ndhead Fantastic. that fixed it. Each drill down shows data each time everytime.

Thank you so much!
