### ISSUE TITLE
How to setup lookup external workflow action?

### ISSUE THREAD

**Issue by TheRealItzik** [alertmanager/alert_manager#257]
I'm new to Alert Manager and I can't find any documentation that really helps.
Can anybody help me and explain to me what do I need to setup on the app/server to be able to setup an EWA that sends an output of an alert to lookup?

**Comment by my2ndhead** [comment]
That's not how it's meant to be used. The EWA allows you to manually call custom alert actions. It basically just runs a | sendalert command with param.* you specify.

I understand you are looking for something that updates a lookup-table? For this you would need to write your own custom alert action.

**Comment by TheRealItzik** [comment]
Thanks for your reply, but I decided to stick to drilldown actions, but I
do need some help with it as well. I have an alert running that shows
events with specific fields. I want to create a drilldown which opens
another search in splunk that shows the amount of events (count) by those
fields shown by the events. The important fields are:
Usernames which are shown like this: <Domain Name>\\<Username>.
Host Names which are shown as the FQDN of the domain (example:
pc1.domain.com).
I have 2 problems:
1) How do I send a token to a URL if the token might start with numbers
(which for some reason doesn't appear to search properly. If you know why
I'd be happy to know why).
2) My indexes are parsed in a way that the one backslash is doubled to
avoid escape sequences. There for to search properly, I need to pass the
token with double the amount of backslashes so it would fit the syntax and
be able to search properly. For example, if I have a username:
Domain\\User1, I'd need to pass a token that contains Domain\\\\User1.
Thank you so much for your help :)

**Comment by TheRealItzik** [comment]
In addition, if you have examples of some complex drilldowns, I'd be happy
to see them
