### ISSUE TITLE
Windows path names in inputs.conf

### ISSUE THREAD

**Issue by afxmac** [alertmanager/alert_manager#262]
Hi,
could not get the app to show me alerts, found the following in the log:
`08-05-2020 12:07:18.673 +0200 ERROR ExecProcessor - Skipping stanza "script://.\bin\alert_manager_scheduler.path": invalid or missing scripted input pointer file

08-05-2020 12:07:18.673 +0200 ERROR ExecProcessor - Unable to open scripted input pointer file ".\bin\alert_manager_scheduler.path": No such file or directory
`
Looked at inputs.conf and found more windows path names:
`$ egrep '\\' inputs.conf`
`[script://.\bin\alert_manager_scheduler.path]`
`[script://.\bin\alert_manager_migrate-v2.0.path]`
`[script://.\bin\alert_manager_migrate-v2.1.path]`
`[script://.\bin\alert_manager_migrate-v2.2.path]`
`[script://.\bin\alert_manager_migrate-v3.0.path]`

This of course will not work on a Linux Splunk Server ,-(

looks like alert_manager_scheduler.path also suffers from this issue.

**Comment by my2ndhead** [comment]
You can ignore this error on a Linux System. The .path file are for Windows only. You could create a stanza under local/inputs.conf to disable the windows scripts.

This will be fixed further down the road, when implementing the migration scripts as platform independent modular inputs.

**Comment by afxmac** [comment]
Hmm, OK, I stumbled across this while trying to figure out while I see none of the alerts. 
After I fixed the Windows specifics the errors are gone of course. 
Still trying to figure out why. at the moment I am stuck with "KV Store is not yet available" even though Splunk thinks KV store is just fine.

**Comment by my2ndhead** [comment]
For the moment you could try to comment out the three lines of the while loop. Maybe there's something in the check that's not working correctly.

**Comment by afxmac** [comment]
Thanks, that killed those error messages. Still no events ,-(

**Comment by my2ndhead** [comment]
Can you open the "health check" dashboard?

**Comment by afxmac** [comment]
Yes everything green apart from the roles which are orange (Warning) about non admin users being assigned to the admin_manager* roles.
I am currently working with full admin privileges.

**Comment by my2ndhead** [comment]
Is everything working now?

**Comment by afxmac** [comment]
Yes, perfectly fine now. 
Already working on adjusting my alerts to make better use of the manager.

**Comment by my2ndhead** [comment]
Ok, closing this issue
