### ISSUE TITLE
Cannot set status to Resolved (False Positive)

### ISSUE THREAD

**Issue by afxmac** [alertmanager/alert_manager#265]
I unhid the false_positive_resolved in alert_status.csv, restarted splunkd but I still cannot set incidents to that status, it is not offered in the edit popup.
Am I missing another spot to enable it?
thx
afx

**Comment by my2ndhead** [comment]
The Alert Status must be set under Settings->Alert Status.

The CSV is just a backup, should the KV Store table be corrupted etc.

**Comment by afxmac** [comment]
Ahh, Pilot error..
Thank you!

**Comment by afxmac** [comment]
A bit weird. I cannot remove the internal_only flag via the screen from the app.
But I could use the lookup editor app to change the KV table. 
All is fine now.

**Comment by my2ndhead** [comment]
The status should not be internal. It's a bug that will be fixed it in the next release
