### ISSUE TITLE
Document what 'sharing scope' alerts must have

### ISSUE THREAD

**Issue by wheresrhys** [alertmanager/alert_manager#271]
I think I've figured out that only alerts with 'Global' sharing are picked up by alert manager, but as far as I can see this isn't documented anywhere. I'm not clear if this is something that can be configured to work with alerts configured with `App` level sharing, or if it is a limitation of the app.

**Comment by my2ndhead** [comment]
Unfortunately, this is a limitation of Splunk. To see an knowledge object under the alerts view from another app you need to share the alert globally.

**Comment by wheresrhys** [comment]
It'd be good if you could document this all the same - it would have saved me and my team a lot of wasted effort
